# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
localizedSettings:
  developerEmail:
  developerName:
  displayName: Prueba de pregunta simple
  fullDescription: Una aplicación que te hace la última pregunta.
  largeBannerImage: $resources.images.landscape
  privacyPolicyUrl:
  pronunciation: Prueba de pregunta simple
  shortDescription: Una aplicación que te hace la última pregunta.
  smallLogoImage: $resources.images.smallLogo
  termsOfServiceUrl:
  themeCustomization:
    landscapeBackgroundImage: $resources.images.landscape
    portraitBackgroundImage: $resources.images.portrait
